### ISSUE TITLE
Add support for .env s inside folders, ex: a "config" folder.

### ISSUE THREAD

**Issue by Nethrenial** [jpruliere/env-autocomplete#19]
# Feature
Add support for .env s inside folders, ex: a "config" folder.

# Description
I took a look at the code base and realized it's just a matter of changing the glob pattern. Is there any chance of changing it so the extension can provide IntelliSense based on .env files residing in directories other than the root directory?
If you guys have no objection to that addition to the extension, can I create a pull request. Or am I free to develop a port for this extension? I was wondering 'cuz there isn't a license file available.

**Comment by maxcutlyp** [comment]
Sure, you can go ahead and create a PR if you'd like, I'll be happy to review it.

Edit: also bear in mind that the latest version available on the VSCode extension marketplace is older than the latest version on GitHub, so you'll need to use the build instructions in the readme. We're in a sort of migration period at the moment as the original creator hasn't had enough time to maintain it. I don't have publishing permissions for the extension yet so I haven't been able to, and although there are plans for that, I haven't heard from @jpruliere for a while so I'll give him a quick ping here.

**Comment by maxcutlyp** [comment]
Hey, just looking for an update on this - did you want to make a PR for this issue? If not I can do it, as you said it's just a matter of changing the glob pattern, but I don't want to step on your toes or do it if you were already planning to.

**Comment by Nethrenial** [comment]
I appreciate it if you can do it, I was suddenly got into some personal problems so didn't have a time to look into it.

**Comment by maxcutlyp** [comment]
No problem, done :)
