### ISSUE TITLE
Load Variables From Other .env Files

### ISSUE THREAD

**Issue by zjr** [jpruliere/env-autocomplete#2]
Hello! Thanks for publishing this extension!

This issue is to note that the extension only loads information from the base `.env` file, however, many users are likely to also have files like `.env.local`, `.env.production`, or `.env.production.local`. The format is something like `.env[.environment][.local]` where `local` is used for files that should not be published.

I would be happy to submit a PR for this if I manage to get the time.

**Comment by jpruliere** [comment]
Hi !

> I would be happy to submit a PR for this if I manage to get the time.

Sounds like a great plan ! This extension was developed for a small internal need but I am glad to see it used by other people :heart_eyes:

**Comment by GorvGoyl** [comment]
adding support for custom `.env` files would be great. NextJS project picks `.env.local` over `.env` files for local development.

It's good project @jpruliere and we can clearly see it's providing value.
