### ISSUE TITLE
Typescript not supported

### ISSUE THREAD

**Issue by JeisonJHA** [jpruliere/env-autocomplete#3]
Hey! Nice extension!

That's an old necessity of mine to auto-complete .env.

I noticed that only javascript is supported(unfortunately), are you open for PR?

Maybe I can send a change for that.

**Comment by jpruliere** [comment]
Hi Jeison ! I am always open to enhancements, that would be great !

Considering the size of the project and my busy agenda, contributing is not restricted in any way (but good practices and changelog updates are much appreciated :wink:).

This extension garners more attention than I thought, I am gonna open a few feature requests to make it decent (test suite, contribution guidelines mostly). In the meantime, consider yourself a pioneer :pick:
