### ISSUE TITLE
Requirement for dotenv in package.json breaks NextJS

### ISSUE THREAD

**Issue by zoeyprobably** [jpruliere/env-autocomplete#5]
NextJS uses dotenv internally, letting the user use it as well. However, dotenv won't appear in the project's top-level package.json file, which causes this extension not to work.

**Comment by GorvGoyl** [comment]
facing the same issue.
@jpruliere could you please merge this PR and release a new version.

**Comment by jpruliere** [comment]
Hi!
Sorry, I am really late on this project. I'll try to release this week :pray:

**Comment by jpruliere** [comment]
release in the pipe, should be good any minute
